#cloud-config
bootcmd:
  - echo "[default]" > /home/ubuntu/.aws/credentials
  - echo "aws_access_key_id=`curl metadata.udf/cloudAccounts/0/apiKey`" >> /home/ubuntu/.aws/credentials
  - echo "aws_secret_access_key=`curl metadata.udf/cloudAccounts/0/apiSecret`" >> /home/ubuntu/.aws/credentials
